### PR TITLE
Adding invoices.email.create() endpoint

### PR DESCRIPTION
**Pull request by davibq**

### CODE REVIEW

**Comment by philals** [comment]
Thanks David. Spot on with everything code wise.

This has got me thinking. Would developers expect a `{}` or `null` when the XeroAPI returns an empty response. 

I think this is the first empty response we have dealt with - so we're defining the contract for all future empty responses.

**Comment by MJMortimer** [comment]
@philals if you've got DELETE for the Item or Account endpoints then these should already be handling NoContent responses I think, so may be best to look at what you do for those?

**Comment by davibq** [comment]
Thanks for the feedback.
Fixed it to return null like DELETE Item and LinkTransactions.

**Comment by philals** [comment]
Thanks @davibq for your contribution. Accepting and releasing soon.

**Comment by philals** [comment]
Thanks @davibq and @MJMortimer 

All published

**Comment by Youdaman** [comment]
How does this endpoint/function work? I tried the following (after fetching an invoice):
```
let email = await xero.invoices.email.create({InvoiceID: invoice.Id})
```
However I got the following error:
```
UnhandledPromiseRejectionWarning: Error: XeroError: statusCode=404 data=The resource you're looking for cannot be found
```
Looking at the API docs (see "Emailing an invoice" here https://developer.xero.com/documentation/api/invoices) I noticed the status can't be draft, so I tried authorised but no dice.

Any hints appreciated!

**Comment by philals** [comment]
Hi @Youdaman 

Have you seen these tests: https://github.com/XeroAPI/xero-node/blob/3601d7453249aa89f34d4dd93459acbc608bc8db/src/__integration_tests__/invoices.integration.tests.ts#L69

That test works, as I get the emails.

Let me know if you need a hand.

**Pull request merged**
