### PR TITLE
Moves express, express-handlebars, mustache and nyc to dev-dependancy

### PR DESCRIPTION
**Pull request by philals**
Hey @jordanwalsh23 

Nice meeting you the other day. Good work with this.

I think the express stuff was in the dependencies due to the sample app. I also moved nyc to dev-dependency.

I ran npm i and yarn install which updated the lock files for both package managers.

All the tests were green except one. I don't think it was because of my changes, but have not confirmed yet.

image

### CODE REVIEW

**Comment by jordanwalsh23** [comment]
Thanks @philals.

Yea that test is a bit painful.  

It's a counting the number of contacts that have been modified in the last 30 seconds.  If all goes according to plan, the test prior modifies a contact, so when this runs it should only return one result.

The problem is that sometimes it takes longer to run a few tests, and you end up modifying the contact 30+ seconds prior.  Which means this test returns 0 results, which means it fails.

I should harden it, but normally what I do is just bump up the 30 seconds to 60 seconds if I need the tests to pass.

I'll review the changes and merge it in tomorrow.

**Comment by philals** [comment]
Cheers @jordanwalsh23 

No rush on the PR.

Is that to test to test xero-nodes modifiedsince handling? Or to test that it's updating a contact?

Just thinking about it....

**Comment by jordanwalsh23** [comment]
It's purpose is to test whether the modifiedsince parameter works as
expected on the contacts helper.  It's more a regression test than anything
else.

**Comment by philals** [comment]
Cool. Nice.

Can't think of a better way to test it right now.

**Comment by philals** [comment]
Added a commit that removes the package-lock.json

Will only use yarn from now

**Comment by philals** [comment]
https://github.com/XeroAPI/xero-node/pull/53 is my preferred on to go first. 

I'll re-update the lock file once that's in.

**Comment by jordanwalsh23** [comment]
#53 merged.  Can you please push with the latest lock file and I'll review.  Thx!

**Comment by philals** [comment]
Cheers @jordanwalsh23 All green

**Pull request merged**
