### PR TITLE
Feature/manual journals

### PR DESCRIPTION
**Pull request by Kamisama666**
I have added support for the Manual Journal section of the API.

I believe I have done everything needed for it to integrate with the rest of the application, including testing and documentation. If there's something missing or any mistake I haven't seen let me know and I'll fix it.

### CODE REVIEW

**Comment by jordanwalsh23** [comment]
Great. Thanks for the effort. I'll review today and let you know.

**Comment by jordanwalsh23** [comment]
The tests aren't passing for me unfortunately.

- There's an undefined reference to `invoice` on line 2272 of accountingtests.js.
- There's a console.log statement on line 34 of manualjournals.js

And the error i'm getting is:
```
2017-05-18 11:21:28.696] [ERROR] [default] - TypeError: Cannot read property 'split' of undefined
    at Function.deepResult (/Users/jordan.walsh/Projects/community-sdks/node-js/xero-node/lib/inde
x.js:1:4475)
    at constructor.convertEntities (/Users/jordan.walsh/Projects/community-sdks/node-js/xero-node/
lib/application.js:12:2226)
```

Can you please fix up these errors making sure the tests pass prior to submission.

Also, can you please update the sample application to have a page for Manual Journals.

Thanks!

**Comment by Kamisama666** [comment]
I'll fix that. But I have a couple of problems:

- I cannot see the console.log statement on accountingtests.js in that line. And the diff doesn't show any added line in that part of the file.
- I'm having a problem running the tests. I'm running them with a private app account and I keep getting this error:

``` 
1) regression tests "before all" hook: create a bank account:
     Error: PUT call failed with: 400 and exception: {
  "$": {
    "xmlns:xsd": "http://www.w3.org/2001/XMLSchema",
    "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
  },
  "ErrorNumber": "10",
  "Type": "ValidationException",
  "Message": "A validation exception occurred",
  "Elements": {
    "DataContractBase": {
      "$": {
        "xsi:type": "Account"
      },
      "ValidationErrors": {
        "ValidationError": {
          "Message": "The Bank Account Number must contain a 6-digit sort code and account number"
        }
      },
      "AccountID": "00000000-0000-0000-0000-000000000000",
      "Code": "4692d48f40",
      "Name": "Test account from Node SDK 4692d48f-4048-458b-8845-b95e7ee4a803",
      "Type": "BANK",
      "BankAccountNumber": "062-021-0000000"
    }
  }
}
      at lib\application.js:3:2063
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

I don't think it's related to my code but rather to my configuration or to my account. The testing_config I'm using looks like this (with the important data changed):

```json
{
    "APPTYPE": "PRIVATE",
    "private": {
        "consumerKey": "MONTYJYGPQT10CFXBJUFURJTSA211JU",
        "consumerSecret": "DFJNLPPEQFTUDDQVFMRNUCHKK6010Y",
        "privateKeyPath": "C:\\Users\\myname\\workspace\\privatekey.pem",
        "userAgent": "Test Integration"
    }
}
```

Any idea what could be the problem?

**Comment by jordanwalsh23** [comment]
I think it could be the region of your account.  I've set this up so that the tests run on an AU account.  Is your Xero Org an AU org or is it in a different region?

**Comment by Kamisama666** [comment]
Hi.

I've fixed the problem with the missing reference and removed the console.log statement.

My account is registered on the UK most likely. Let me know if there's something I can do myself to run the tests, but otherwise I'm assigning it back to you.

**Comment by jordanwalsh23** [comment]
I've merged this as part of PR#24.

Thanks for your contribution 👍

**Comment by jordanwalsh23** [comment]
Also @Kamisama666, I recommend regenerating your consumerkey and secret from within the developer portal as you have published them above.

**Pull request merged**
