### PR TITLE
Enable getting creditNotes by CreditNoteNumber

### PR DESCRIPTION
**Pull request by gslisrael**
Enable getting creditNotes by CreditNoteNumber much like you can get invoices by InvoiceNumber

### CODE REVIEW

**Comment by philals** [comment]
Thanks a lot.

This is wicked! Do you mind adding one test in this file - just like InvoiceNumber? https://github.com/XeroAPI/xero-node/blob/master/src/__tests__/AccountingAPI-endpoint.tests.ts#L136

Tag me once you have updated this and I'll release ASAP for ya!

**Comment by gslisrael** [comment]
Tagging @philals . I added the test. I hope I did this correctly. I'm still new to contributing to github.

**Comment by philals** [comment]
Perfect. Thanks for that! Have pushed your changes in the latest version.

**Comment by gslisrael** [comment]
Thank you. I'm happy to contribute.

**Pull request merged**
