### PR TITLE
add correct Content-Length header for attachments

### LINKED ISSUE #217: Attachments returning 411: Length required
**v2.20.0**

```
const data = {
    FileName: path.basename(filePath),
    MimeType: 'application/pdf'
  }

  const fileReadStream = fs.createReadStream(filePath)
  const attachmentObj = xeroClient.core.attachments.newAttachment(data)

  return attachmentObj.save('Invoices/' + invoice.InvoiceID, fileReadStream, true)
```

### PR DESCRIPTION
**Pull request by JacobDorman**
Fixes #217

### CODE REVIEW

**Comment by philals** [comment]
Hi @JacobDorman I don't have V2 set up and ready to go, and don't have time run the code.

Can you confirm that you have this code path executed and working on your machine?

One confirmed I'll merge and release a new V2.

**Comment by lucasbedout** [comment]
Does not work for streams @JacobDorman, just tried

**Comment by philals** [comment]
Hi just following up.

Is this still an issue? I'll code in a few days otherwise. Thanks

**Comment by lucasbedout** [comment]
I upgraded to V3 but it's still an issue for anyone using this version of the SDK

**Comment by philals** [comment]
Thanks @lucasbedout 

I'll close for now and remember for anyone else that raises this issue to reference back here. Once there is someone else wanting it then we'll pick it up again.

I'm hesitant to accept and publish changes to V2 that I cannot support directly.

Thanks for your input. Much appreciated.

**Pull request closed without merging**
