### PR TITLE
Add optional chaining to ensure compatibility with mocking library

### PR DESCRIPTION
**Pull request by QuentinLemCode**
Solve #675

### CODE REVIEW

**Comment by TiddoLangerak** [comment]
I'm not quite sure if this is desirable, as this changes the contract (thus is a breaking change). I  wouldn't expect the values to be `undefined` in tests (or anywhere else for that matter). I think the minimal change needed to make this work with `nock` is to replace `port: axiosError.request.agent.defaultPort,` with `port: axiosError.request.socket.localPort` - without optional chaining. This preserves the contract, and thus is a non-breaking change that addresses the issue.

**Comment by QuentinLemCode** [comment]
> I'm not quite sure if this is desirable, as this changes the contract (thus is a breaking change). I wouldn't expect the values to be `undefined` in tests (or anywhere else for that matter). I think the minimal change needed to make this work with `nock` is to replace `port: axiosError.request.agent.defaultPort,` with `port: axiosError.request.socket.localPort` - without optional chaining. This preserves the contract, and thus is a non-breaking change that addresses the issue.

I'd rather update the contract. 
I'm not sure the object `socket` is always present. Do you have documentation about that?

**Comment by TiddoLangerak** [comment]
https://nodejs.org/api/http.html#requestsocket

**Comment by QuentinLemCode** [comment]
> axiosError.request.socket.localPort

@TiddoLangerak 
Thanks, but I'm still unsure that this object is **always** present
There can be cases where the request has not been done yet : request cancellation, request interceptor failed, payload transform error ... 

The `request` object is marked as optional in the [Axios type definitio](https://github.com/axios/axios/blob/main/index.d.ts)n. We should reflect this in the ApiError type definition.

**Comment by sangeet-joy-tw** [comment]
The issue has been addressed in our latest xero-node v7.0.0. Hence closing this PR.

**Pull request closed without merging**
