### PR TITLE
404s are returned from API as text/html

### PR DESCRIPTION
**Pull request by philals**

### CODE REVIEW

**Comment by philals** [comment]
image

**Comment by philals** [comment]
@dupski just checking on this test. 

It passed for you? From the looks of it 404s are returned as per the fiddler screen shot.

**Comment by dupski** [comment]
Afternoon @philals . Did you set your "Accepts" header when making the request with fiddler? When I tested I was getting JSON responses with a statusCode that was a number. If you need to do a "contains" I would expect that to be on the complete data rather than just the statusCode field.

**Comment by philals** [comment]
So here I have intercepted the request from the .NET SDK (setting up fiddler with Node is a bit of a chore).

image

It's because of this line here which looks to be not doing what is intended:

` err = { statusCode: res.statusCode + " but response content-type of " + contentType + " did not match the Accept Header of " + contentType.toLowerCase() };`

Looks like it's Sid's code from a PDF issue. 

I'm trying to figure out how the test passed for you. 

We'll rerun them when in the office on your computer.

**Pull request closed without merging**
