### PR TITLE
Replace underscore with lodash and native equivalent methods

### PR DESCRIPTION
**Pull request by warp**

### CODE REVIEW

**Comment by warp** [comment]
@philals I am happy to rebase this one if that is helpful

**Comment by philals** [comment]
@warp yes please.

**Comment by warp** [comment]
@philals I have rebased the changes I don't have xero credentials set up to run all tests locally so it would pay to give the test suite a run before merging

**Comment by philals** [comment]
Cheers.

I am getting this error when I run the tests:

`TypeError: schema.bla is not a function
    at constructor.<anonymous> (C:\Dev\xero-node\lib\schemaobject\schemaobject.js:83:31)
    at constructor (C:\Dev\xero-node\lib\entities\entity.js:1:6112)
    at new constructor (C:\Dev\xero-node\lib\entities\accounting\organisation.js:1:3358)
    at Object.clonedOptions.entityConstructor (C:\Dev\xero-node\lib\entity_helpers\accounting\organisations.js:1:4100)
    at addEntity (C:\Dev\xero-node\lib\application.js:17:3207)
    at C:\Dev\xero-node\lib\application.js:17:2966
    at Array.forEach (<anonymous>)
    at constructor.convertEntities (C:\Dev\xero-node\lib\application.js:17:2891)
    at C:\Dev\xero-node\lib\application.js:17:4571
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`


It's actually on line 358.

**Comment by philals** [comment]
Replacing it with 
` Object.keys(schema).forEach(function(properties, index) {`

Also I think 616 needs to be 
`         Object.keys(this._instance._schema).forEach(function(properties, index) { `

Still testing....

**Comment by philals** [comment]
So I there is an issue is schemaobject. There are places where a var called defaults is used, and we want to import it from lodash.

I find it quite hard to even figure out what's going on in that file.

**Comment by warp** [comment]
@philals sorry it took me a while to get back to this I have fixed the incorrect usage of object forEach and the variable conflict with defaults.

**Comment by philals** [comment]
No worries. @warp. We're in the middle of sprint at the moment. So I'll take a look after.

**Comment by philals** [comment]
Hi @warp Just checking, are you running the tests?

**Comment by warp** [comment]
@philals Not well I had trouble setting up the test credentials in testing_config.json do you have a standard set of credentials you use for testing?

**Comment by philals** [comment]
I only have mine, which includes all my secrets.

Does this help? I have x'd out my secrets.

image

**Comment by warp** [comment]
@philals Ok I had tried a public and a partner app I didn't think to try a private one I have the tests running correctly now so I'll fix up the remaining issues.

**Comment by warp** [comment]
@philals I fixed a couple more issues. I still have some tests failing but they appear to be related to the demo app configuration rather than code. It would be great if CI could be set up to run against a known good app.

**Comment by philals** [comment]
@warp 

Cheers. Yeah, there are some tests which fail depending on the country of the org etc. I mainly looks the code exceptions. Will try to process this tomorrow.

CI is on the list of things to do. I welcome any one to set it up - and I'll connect it to pull requests.

**Comment by philals** [comment]
Hi @warp 

Sorry we never got this done.

We have released a fully re written version that has tests which run in CI.

Please check it out.

All the best

**Pull request closed without merging**
