### PR TITLE
Fix handling of projectIds argument in projects.get

### PR DESCRIPTION
**Pull request by thehappycoder**

### CODE REVIEW

**Comment by SidneyAllen** [comment]
@thehappycoder and @jeepman32 

Just an update on this PR - we have not forgotten this.  I'll be working on the Projects OpenAPI Spec over the next couple weeks to prepare for use to generate these endpoints for our SDKs.  Thanks for you patience on this.

**Comment by SerKnight** [comment]
@RettBehrens - ping here as a reminder - we should see in sample app if this functionality is fixed: 

projectId | You can specify an individual project by appending the projectId to the endpoint, i.e. GET https://.../projects/{projectId}
-- | --
projectIds | Search for all projects that match a comma separated list of projectIds, i.e. GET https://.../projects?projectIDs={projectId},{projectId}

**Comment by RettBehrens** [comment]
@SerKnight this is working correctly in the [sample app](https://github.com/XeroAPI/xero-node-oauth2-app) using 4.4.8

`
//GET ALL
const getAllResponse = await xero.projectApi.getProjects(req.session.activeTenant.tenantId);

//GET MULTIPLE SPECIFIED
const getMultipleSpecifiedResponse = await xero.projectApi.getProjects(req.session.activeTenant.tenantId, [getAllResponse.body.items[0].projectId, getAllResponse.body.items[1].projectId]);
`

**Comment by SerKnight** [comment]
Xero projects API functionality has been added in this release: https://github.com/XeroAPI/xero-node/releases/tag/4.4.8

Thank you for your patience on this one!

**Pull request closed without merging**
