### PR TITLE
Support Pojects #215. No tests done

### PR DESCRIPTION
**Pull request by jamespwilson**

### CODE REVIEW

**Comment by philals** [comment]
Wow thanks for that.

I'll have to make some time to go through it.

Please only implement a minimal number of endpoint to make it easier to get the PR in. Once we have that in master then adding more should be easy.

**Comment by jamespwilson** [comment]
Ok. I have added 3 endpoints. How many should i have added?

**Comment by philals** [comment]
@jamespwilson 3 is perfect!

Having a small number just makes getting the pattern easier to sort out. 

I should have some time tomorrow (NZ) to get this going.

**Comment by philals** [comment]
Sorry just getting to this.

So our original intent on having a class call AccountingAPIClient is that for each new API we add then we will have another class. 

For example PayrollAPIClient and ProjectsAPIClient.

Let's give that a go.

**Comment by philals** [comment]
Same with the src/AccountingAPI-models.ts. 

Let's try src/ProjectsAPI-models.ts

**Comment by jamespwilson** [comment]
That would be fine by me. Can you make the change?

**Comment by philals** [comment]
Hi @jamespwilson 

I can't push to your branch. So I have taken your commits and opened a new PR with the changes above: #221 

I have trimmed back to one endpoint GET on /projects. I have also added unit tests for this. I'll get access to the Projects Beta.

Feel free to PR into this branch. Once we have a good pattern laid out for this one endpoint then we'll work on the others.

**Pull request closed without merging**
